"""Fix KeyMessage foreign keys to employees table

Revision ID: 138e16c23721
Revises: 67287b535d5e
Create Date: 2025-05-15 18:11:15.523170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '138e16c23721'
down_revision = '67287b535d5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('key_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('supporting_statement', sa.Text(), nullable=False),
    sa.Column('tone_purpose', sa.String(length=100), nullable=False),
    sa.Column('stage_tag', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('key_message_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key_message_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('supporting_statement', sa.Text(), nullable=False),
    sa.Column('tone_purpose', sa.String(length=100), nullable=False),
    sa.Column('stage_tag', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.Column('changed_by_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['key_message_id'], ['key_message.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('key_message_history')
    op.drop_table('key_message')
    # ### end Alembic commands ###
