# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Deploy full backend folder via Kudu Zip Deploy (.war trick)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Create virtual environment and install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r backend/requirements.txt

      - name: Zip entire backend folder
        run: |
          zip -r deploy.war backend -x "backend/venv/*"

      - name: List contents of deploy.war
        run: unzip -l deploy.war

      - name: Deploy using raw Kudu Zip Deploy (.war trick)
        run: |
          curl -X POST "https://changemanagement-backend-ahfre3hvgcerbrgp.scm.canadacentral-01.azurewebsites.net/api/zipdeploy" \
          -u ${{ secrets.AZURE_DEPLOY_USER }}:${{ secrets.AZURE_DEPLOY_PASSWORD }} \
          --data-binary @"deploy.war"
