# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions
name: Build and package backend for Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-zip:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Create virtual environment and install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r backend/requirements.txt

      - name: Zip backend contents (flattened structure)
        run: |
          cd backend
          zip -r ../deploy.zip .

      - name: List contents of deploy.zip
        run: unzip -l deploy.zip

      - name: Upload deploy.zip as artifact
        uses: actions/upload-artifact@v4
        with:
          name: deploy-package
          path: deploy.zip
